### PR TITLE
Corrections to work with angular 13

### LINKED ISSUE #76: Doesn't work with Angular 12.2 anymore
**Describe the bug**
When I create a new Angular application and apply the schematics, the tests immediately fail.

```
Schema validation failed with the following errors:
Data path "/polyfills" must be array.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-cli-jest@0.0.0 test: `ng test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-cli-jest@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**To Reproduce**
```bash
npx @angular/cli@12 new angular-cli-jest
npx ng add @briebug/jest-schematic
npm run test
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Node version: 14.16.0
 - NPM or Yarn version: NPM 6.14.11
 - App type Angular CLI
 - Angular version 12.2

### LINKED ISSUE #77: Angular 13 - NOT SUPPORTED: keyword "id", use "$id" for schema ID
**Describe the bug**
Trying to run `ng add @briebug/jest-schematic`
Get the following error
```
ng add @briebug/jest-schematic
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
See "C:\Users\montei0m\AppData\Local\Temp\ng-p0TjR2\angular-errors.log" for further details.
```

SAME ISSUE WITH THE GLOBALLY INSTALLED
**To Reproduce**
image

**Expected behavior**
That works as in the gif of your readme file
image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Windows] Windows
 - Node version: [e.g. 8.11.3] 14.17.3
 - NPM or Yarn version [e.g. Yarn 1.3.0] NPM  6.14.7
 - App type [e.g. Angular CLI, Nx Workspace]
 - Angular version [e.g. @angular/core: "6.0.3"]
```
 ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.0.1
Node: 14.17.3
Package Manager: npm 6.14.7
OS: win32 x64

Angular: 13.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            13.0.1
@angular-devkit/schematics      13.0.1
@angular/cli                    13.0.1
@schematics/angular             13.0.1
rxjs                            7.4.0
typescript                      4.4.4
```

**Additional context**

### PR DESCRIPTION
**Pull request by patou**
fix #77 
fix #76 

Corrections of the schematic : 
- Use $id instead of id in the schema.json
- Delete polyfills and inlineStyleLanguage in angular.json (config not used in the new jest builder).
- Migrate all sandboxes projects to angular 13
- Update jestconfig files in workspace with new format.
- Update node version in the circleci to 16
- Add other dependency to remove in project

Ready to review

### CODE REVIEW

**Review by webstik1811 — APPROVED** [review]

**Review by webstik1811 — APPROVED** [review]

**Comment by patou** [comment]
@schuchard any update for this PR ?

**Comment by patou** [comment]
I publish the correction on a new package npm : 
https://www.npmjs.com/package/@patoudss/jest-schematic

Juste do : 
```
ng add @patoudss/jest-schematic 
```

**Comment by schuchard** [comment]
@patou, apologies on the delayed response. I've reviewed the PR and it looks good. Would you mind rebasing now that I've merged some other PR's so that I can get this in and test it. Additionally, please retarget this PR for https://github.com/briebug/jest-schematic/tree/feat/support-ng-13.

Thank you

**Comment by patou** [comment]
@schuchard I rebase this branche to `feat/support-ng-13`

**Review by schuchard — APPROVED** [review]

**Pull request merged**
